# Generated by Django 3.0.6 on 2020-06-26 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlık')),
                ('content', models.TextField(blank=True, max_length=100, null=True, verbose_name='Açıklama')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mahalle')),
                ('zipcode', models.CharField(blank=True, max_length=12, null=True, verbose_name='ZIP / Postal code')),
                ('adress', models.TextField(blank=True, null=True, verbose_name='Açık Adres')),
                ('facade1', models.ImageField(blank=True, default='profile_picture/default.jpg', null=True, upload_to='buildings{instance.user}')),
                ('facade2', models.ImageField(blank=True, default='profile_picture/default.jpg', null=True, upload_to='buildings')),
                ('facade3', models.ImageField(blank=True, default='profile_picture/default.jpg', null=True, upload_to='buildings')),
                ('facade4', models.ImageField(blank=True, default='profile_picture/default.jpg', null=True, upload_to='buildings')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
