# Generated by Django 3.0.6 on 2020-06-26 14:48

from django.db import migrations, models
import entry.models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20200626_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='facade2',
            field=models.ImageField(blank=True, default='profile_picture/default.jpg', null=True, upload_to=entry.models.user_directory_path1),
        ),
    ]
