# Generated by Django 3.0.6 on 2020-06-26 14:49

from django.db import migrations, models
import entry.models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_auto_20200626_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='facade1',
            field=models.ImageField(blank=True, default='profile_picture/default.jpg', null=True, upload_to=entry.models.user_directory_path1),
        ),
        migrations.AlterField(
            model_name='entry',
            name='facade2',
            field=models.ImageField(blank=True, default='profile_picture/default.jpg', null=True, upload_to=entry.models.user_directory_path2),
        ),
        migrations.AlterField(
            model_name='entry',
            name='facade3',
            field=models.ImageField(blank=True, default='profile_picture/default.jpg', null=True, upload_to=entry.models.user_directory_path3),
        ),
        migrations.AlterField(
            model_name='entry',
            name='facade4',
            field=models.ImageField(blank=True, default='profile_picture/default.jpg', null=True, upload_to=entry.models.user_directory_path4),
        ),
    ]
