# Generated by Django 3.0.6 on 2020-07-19 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0010_remove_entry_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Oluşturan', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
