# Generated by Django 3.0.6 on 2020-07-19 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0013_auto_20200719_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanıcıadı', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
