# Generated by Django 3.0.6 on 2020-07-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0014_auto_20200719_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='username',
        ),
    ]
