# Generated by Django 3.0.6 on 2020-06-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='profile_picture/default.jpg', null=True, upload_to='profile_picture')),
                ('education_bs', models.CharField(blank=True, max_length=100, null=True)),
                ('education_master', models.CharField(blank=True, max_length=100, null=True)),
                ('education_phd', models.CharField(blank=True, max_length=100, null=True)),
                ('current_departmant', models.CharField(blank=True, max_length=100, null=True)),
                ('current_university', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('detailed_cv', models.URLField(blank=True, null=True)),
                ('resarch_interest', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('room_number', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.IntegerField(blank=True, default='1', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'ordering': ['-rank'],
            },
        ),
        migrations.CreateModel(
            name='Resarcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='profile_picture/default.jpg', null=True, upload_to='profile_picture')),
                ('education_bs', models.CharField(blank=True, max_length=100, null=True)),
                ('education_master', models.CharField(blank=True, max_length=100, null=True)),
                ('education_phd', models.CharField(blank=True, max_length=100, null=True)),
                ('current_departmant', models.CharField(blank=True, max_length=100, null=True)),
                ('current_university', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('detailed_cv', models.URLField(blank=True, null=True)),
                ('resarch_interest', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('room_number', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.IntegerField(blank=True, default='1', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'ordering': ['-rank'],
            },
        ),
    ]
