# Generated by Django 3.0.6 on 2020-06-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resarcher',
            new_name='Researcher',
        ),
    ]
