# Generated by Django 3.0.6 on 2020-06-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200626_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborator',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='researcher',
            options={'ordering': ['rank']},
        ),
    ]
