# Generated by Django 3.0.6 on 2020-06-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200626_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaultpp.jpg', null=True, upload_to='profile_picture'),
        ),
    ]
